apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: /etc/kubernetes/resolv.conf
authorization:
  mode: Webhook
authentication:
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
containerRuntimeEndpoint: "unix:///var/run/crio/crio.sock"

