apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - "*"
    resources:
      - leases
      - nodes
      - services
      - secrets
      - persistentvolumes
      - configmaps
      - nodes/status
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
      - pods/status
      - pods/log
      - pods
      - events
      - replicasets
      - deployments
      - clusterroles
      - endpointslices
      - csidrivers
      - serviceaccounts/token
      - replicasets/status
      - apps
      - runtimeclasses
      - csinodes
      - endpoints
      - deployments/status
      - deployments/scale
      - jobs
      - batch
      - jobs/status
      - controllerrevisions
      - statefulsets
      - statefulsets/status 
      - ingresses
      - persistentvolumeclaims
      - storageclasses
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
      - replicasets/scale
      - tokenreviews
      - subjectaccessreviews
      - daemonsets
      - daemonsets/status
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-apiserver
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-apiserver-to-kubelet
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: admin
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:node:kube01.mrgz.org


