---
  - name: "install and upgrade packages"
    hosts: local
    connection: local
    tasks:
      - name: "include vars"
        include_vars:
          file: "../../config.yaml"
          name: "kconf"
      - name: "Reboot to configure and start service"
        kubernetes.core.helm:
          name: coredns
          chart_ref: coredns/coredns
          values_files:
            - '{{kconf.coredns.values_file}}'
          release_namespace: kube-system

