---
  - name: "install and upgrade packages"
    hosts: local
    connection: local
    tasks:
      - name: "include vars"
        include_vars:
          file: "../../config.yaml"
          name: "kconf"
      - name: "Reboot to configure and start service"
        kubernetes.core.helm:
          name: metrics-server 
          chart_ref: metrics-server/metrics-server
          values_files:
            - '{{kconf.metrics_server.values_file}}'
          release_namespace: '{{kconf.metrics_server.namespace}}'

