---
  - name: "Add accept keywords dir"
    file:
      path: "/etc/portage/package.accept_keywords"
      state: directory
  - name: "add cri-o accept keyword file"
    copy:
      src: "../../resources/crio_accept"
      dest: "/etc/portage/package.accept_keywords/crio"
  - name: "kubelet"
    package:
      name: kubelet
      state: installed
  - name: "Install kube-proxy"
    package:
      name: kube-proxy
      state: installed
  - name: "Install cri-o"
    package:
      name: cri-o
      state: installed
  - name: "Install cri-tools"
    package:
      name: cri-tools
      state: installed
  - name: "Install cni-plugins"
    package:
      name: cni-plugins
      state: installed
  - name: "Install runc"
    package:
      name: crun 
      state: installed
  - name: "Install containerd"
    package:
      name: containerd
      state: installed
  - name: "Install conntrack-tools"
    package:
      name: conntrack-tools
      state: installed
  - name: "Install ipvsadm"
    package:
      name: ipvsadm
      state: installed
  - name: "kubectl"
    package:
      name: kubectl
      state: installed
  - name: "ipset"
    package:
      name: ipset
      state: installed
  - name: "chrony"
    package:
      name: chrony
      state: installed
  - name: "Enable chronyd service"
    service:
      name: chronyd
      enabled: yes

