---
    - name: "generate CA pair"
      hosts: local
      connection: local
      tasks:
      - name: "include vars"
        include_vars:
          file: "../../config.yaml"
          name: "kconf"

      - name: "Ensure data dir is created"
        file:
          path: "{{kconf.data_dir}}"
          state: directory
          mode: 0700

      - name: "Copy openssl ca base config"
        copy:
          src: '../../resources/openssl_ca.conf'
          dest: '{{kconf.data_dir}}'
        delegate_to: localhost

      - name: "Replace OpenSSL C"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_C}"
          replace: "{{kconf.openssl_c}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      - name: "Replace OpenSSL ST"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_ST}"
          replace: "{{kconf.openssl_st}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      - name: "Replace OpenSSL ST"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_ST}"
          replace: "{{kconf.openssl_st}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      - name: "Replace OpenSSL L"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_L}"
          replace: "{{kconf.openssl_l}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      - name: "Replace OpenSSL O"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_O}"
          replace: "{{kconf.openssl_o}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      - name: "Replace OpenSSL OU"
        replace:
          path: "{{ item.path }}"
          regexp: "{OPENSSL_OU}"
          replace: "{{kconf.openssl_ou}}"
        with_items:
          - {"path":"{{kconf.data_dir}}/openssl_ca.conf"}
        delegate_to: localhost

      # create ca pair
      - name: "Openssl CA key"
        shell: "openssl genrsa -out {{kconf.data_dir}}/ca.key 2048"
        delegate_to: localhost

      - name: "Openssl CA crt"
        shell: 'openssl req -x509 -new -nodes -key {{kconf.data_dir}}/ca.key -days 10000 -out {{kconf.data_dir}}/ca.crt -extensions v3_ext -config {{kconf.data_dir}}/openssl_ca.conf'
        delegate_to: localhost

