---
    # creates pki dir
    - name: "Kubernetes PKI dir"
      file:
        path: "/etc/kubernetes/pki"
        state: directory
        owner: root
        mode: u=rwx,g=rx,o=rx

    - name: "Kubernetes PKI dir"
      file:
        path: "/etc/etcd/pki"
        state: directory
        owner: etcd
        mode: u=rwx,g=rx,o=rx

    # put ssl config files
    - name: "Copy openssl config files"
      copy:
        src: "{{ item.src }}"
        dest: "/etc/kubernetes/pki"
      with_items:
        - {"src":"../resources/openssl.conf"}
        - {"src":"../resources/openssl_ca.conf"}

    - name: "Replace Hostname"
      replace:
        path: "{{ item.path }}"
        regexp: "{HOSTNAME}"
        replace: "{{ansible_hostname}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace IP"
      replace:
        path: "{{ item.path }}"
        regexp: "{INSTANCE_IP}"
        replace: "{{ansible_default_ipv4.address}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace OpenSSL C"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_C}"
        replace: "{{kconf.openssl_c}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace OpenSSL ST"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_ST}"
        replace: "{{kconf.openssl_st}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace OpenSSL L"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_L}"
        replace: "{{kconf.openssl_l}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace OpenSSL O"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_O}"
        replace: "{{kconf.openssl_o}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace OpenSSL OU"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_OU}"
        replace: "{{kconf.openssl_ou}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    - name: "Replace Cluster Name"
      replace:
        path: "{{ item.path }}"
        regexp: "{API_ENDPOINT}"
        replace: "{{kconf.api_endpoint}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}
        - {"path":"/etc/kubernetes/pki/openssl_ca.conf"}

    # create ca pair
    - name: "check ca.key"
      stat:
        path: "/etc/kubernetes/pki/ca.key"
      register: has_cakey
    - name: "Openssl CA key"
      shell: "openssl genrsa -out ca.key 2048"
      args:
        chdir: "/etc/kubernetes/pki"
      when: not has_cakey.stat.exists
    - name: "check ca.crt"
      stat:
        path: "/etc/kubernetes/pki/ca.crt"
      register: has_cacrt
    - name: "Openssl CA crt"
      shell: 'openssl req -x509 -new -nodes -key ca.key -days 10000 -out ca.crt -extensions v3_ext -config openssl_ca.conf'
      args:
        chdir: "/etc/kubernetes/pki"
      when: not has_cacrt.stat.exists
    - name: "Copy ca.key to local"
      fetch:
        src: "/etc/kubernetes/pki/ca.key"
        dest: "../data/ca.key"
        flat: true
    - name: "Copy ca.crt to local"
      fetch:
        src: "/etc/kubernetes/pki/ca.crt"
        dest: "../data/ca.crt"
        flat: true

