---
    # creates pki dir
    - name: "Kubernetes PKI dir"
      file:
        path: "/etc/kubernetes/pki"
        state: directory
        owner: root
        mode: u=rwx,g=rx,o=rx
    - name: "Copy CA cert"
      copy:
        src: "../../data/ca.crt"
        dest: "/etc/kubernetes/pki"
    - name: "Copy CA key"
      copy:
        src: "../../data/ca.key"
        dest: "/etc/kubernetes/pki"

    # put ssl config files
    - name: "Copy openssl config files"
      copy:
        src: "{{ item.src }}"
        dest: "/etc/kubernetes/pki"
      with_items:
        - {"src":"../resources/openssl.conf"}

    - name: "Replace Hostname"
      replace:
        path: "{{ item.path }}"
        regexp: "{HOSTNAME}"
        replace: "{{ansible_hostname}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace IP"
      replace:
        path: "{{ item.path }}"
        regexp: "{INSTANCE_IP}"
        replace: "{{ansible_default_ipv4.address}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace OpenSSL C"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_C}"
        replace: "{{kconf.openssl_c}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace OpenSSL ST"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_ST}"
        replace: "{{kconf.openssl_st}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace OpenSSL L"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_L}"
        replace: "{{kconf.openssl_l}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace OpenSSL O"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_O}"
        replace: "{{kconf.openssl_o}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace OpenSSL OU"
      replace:
        path: "{{ item.path }}"
        regexp: "{OPENSSL_OU}"
        replace: "{{kconf.openssl_ou}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}

    - name: "Replace Cluster Name"
      replace:
        path: "{{ item.path }}"
        regexp: "{API_ENDPOINT}"
        replace: "{{kconf.api_endpoint}}"
      with_items:
        - {"path":"/etc/kubernetes/pki/openssl.conf"}


