---
  # cert common tasks for controlplane and workers
  - name: "check pki dir"
    include_tasks: ../certs/common.yaml

  - name: "Copy CA cert"
    copy:
      src: "{{kconf.data_dir}}/ca.crt"
      dest: "/etc/kubernetes/pki"
  - name: "Copy CA key"
    copy:
      src: "{{kconf.data_dir}}/ca.key"
      dest: "/etc/kubernetes/pki"

  # kubelet cert
  - name: "kubelet key"
    shell: 'openssl genrsa -out kubelet.key 2048'
    args:
      chdir: "/etc/kubernetes/pki"
  - name: "kubelet csr"
    shell: "openssl req -new -key kubelet.key -out kubelet.csr -in openssl.conf -subj \"/O=system:nodes/CN=system:node:{{ansible_hostname}}\""
    args:
      chdir: "/etc/kubernetes/pki"
  - name: "kubelet crt"
    shell: "openssl x509 -req -in kubelet.csr -CA ca.crt -CAkey ca.key -set_serial 101 -days 365 -outform PEM -out kubelet.crt -extensions v3_ext -extfile openssl.conf"
    args:
      chdir: "/etc/kubernetes/pki"

  # kube-proxy cert
  - name: "kube-proxy key"
    shell: 'openssl genrsa -out kube-proxy.key 2048'
    args:
      chdir: "/etc/kubernetes/pki"
  - name: "kube-proxy csr"
    shell: "openssl req -new -key kube-proxy.key -out kube-proxy.csr -in openssl.conf -subj \"/CN=system:kube-proxy\""
    args:
      chdir: "/etc/kubernetes/pki"
  - name: "kube-proxy crt"
    shell: "openssl x509 -req -in kube-proxy.csr -CA ca.crt -CAkey ca.key -set_serial 101 -days 365 -outform PEM -out kube-proxy.crt"
    args:
      chdir: "/etc/kubernetes/pki"

